import fs from "fs";
import path from "path";

export function initProject(rootDir: string) {
  const folders = [
    "src",
    "tests",
    ".github/workflows"
  ];

  folders.forEach((folder) => {
    const folderPath = path.join(
      rootDir,
      folder
    );

    if (!fs.existsSync(folderPath)) {
      fs.mkdirSync(folderPath, {
        recursive: true,
      });

      console.log(`📁 Created ${folder}`);
    }
  });

  const files = [
    {
      name: ".gitignore",
      content:
`node_modules
dist
.env`
    },
    {
      name: "README.md",
      content:
`# Project

Generated by DevScripts CLI`
    },
    {
      name: ".env.example",
      content:
`PORT=3000
DATABASE_URL=`
    },
    {
      name:
".github/workflows/ci.yml",
      content:
`name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run build`
    }
  ];

  files.forEach((file) => {
    const filePath = path.join(
      rootDir,
      file.name
    );

    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(
        filePath,
        file.content
      );

      console.log(`📄 Created ${file.name}`);
    }
  });

  console.log(
    "\n🚀 Project initialized successfully!"
  );
}